from __future__ import annotations

import argparse
import logging
from pathlib import Path

import matplotlib.pyplot as plt
import sinter
from typing_extensions import override

from tqec._cli.subcommands.base import TQECSubCommand


class PlotSubCommand(TQECSubCommand):
    @staticmethod
    @override
    def add_subcommand(
        main_parser: argparse._SubParsersAction[argparse.ArgumentParser],
    ) -> None:
        parser: argparse.ArgumentParser = main_parser.add_parser(
            "plot",
            description=(
                "Plot the results of an existing CSV file from a simulation."
                "Useful to tweak the limits of the plots."
            ),
        )
        parser.add_argument(
            "-d",
            "--directory",
            help="Directory containing all the files generated by TQEC.",
            type=Path,
            default="simulations",
        )
        parser.add_argument(
            "csv_file",
            help="A valid .csv file containing the results of a simulation run by TQEC.",
            type=Path,
        )
        parser.set_defaults(func=PlotSubCommand.execute)

    @staticmethod
    @override
    def execute(args: argparse.Namespace) -> None:
        # Parse args
        logging.info("Parsing arguments.")
        csv_path: Path = args.csv_file.resolve()
        directory: Path = args.directory.resolve()

        print(f"Working on CSV : {csv_path.name}")

        stats = sinter.stats_from_csv_files(csv_path)
        print(f"Stats : {len(stats)}")

        fig, ax = plt.subplots()
        sinter.plot_error_rate(
            ax=ax,
            stats=stats,
            x_func=lambda stat: stat.json_metadata["p"],
            group_func=lambda stat: stat.json_metadata["d"],
        )
        # plot_observable_as_inset(ax, zx_graph, correlation_surfaces[i])
        ax.grid(axis="both")
        ax.set_xlabel("Physical Error Rate")
        ax.set_xlim(1e-4, 0.0125)
        ax.set_ylabel("Logical Error Rate")
        ax.set_ylim(1.25e-9, 1.25)
        ax.legend()
        ax.loglog()
        ax.set_title(f"{csv_path.stem}")
        fig.savefig(f"{directory}/{csv_path.stem}.png")

        print(f"Saved {directory}/{csv_path.stem}.png")
