# .github/workflows/pr-close.yml

name: Delete preview on PR close
on:
  pull_request:
    types: [closed]

jobs:
  delete_preview:
    runs-on: ubuntu-latest
    steps:
      - name: make empty dir
        run: mkdir public
      - name: Push an empty directory to pull/[number]
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
          destination_dir: ./pull/${{github.event.number}}/
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: documentation-preview
          recreate: true
          message: |
            🪓 PR closed, deleted preview at https://tqec.github.io/tqec/pull/${{github.event.number}}/

  # From https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#managing-caches
  cleanup_caches:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup caches generated in this branch
        run: |
          echo "Fetching list of cache keys"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              echo "Deleting cache key '${cacheKey}'..."
              gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
